Improvements
noamyogev84/ConcurrentPriorityQueue pull request #19
Opened 2022-12-30 09:32 UTC by zhuxb711

1. Removed unnecessary lock in some functions
2. Upgrade to latest dependency
3. Upgrade to .Net 7.0
4. Optimize the GetNextQueue and AddOrUpdate to make it faster
5. Clean up the code to fix .Net Analyzers's error
6. Add Equals overrides on TimeToProcess class to fix the failure on GenericPriorityQueueUnitTests

2023-01-01 16:31 UTC, zhuxb711 commented
@noamyogev84 Hi please help review the PR and let me know if have any concerns, thanks! It would be great if you could merge this PR and publish a new version to nuget🙂

2023-01-02 20:05 UTC, noamyogev84 requested changes
Thanks @zhuxb711 ! 💪💪💪

2023-01-02 20:05 UTC, noamyogev84 commented on ConcurrentPriorityQueue/ConcurrentPriorityQueue.csproj
>    </ItemGroup>
remove and update for all in `Directory.Build.props`

2023-01-02 20:05 UTC, noamyogev84 commented on ConcurrentPriorityQueue/Core/ConcurrentPriorityQueue.cs
> +        public int Count => _internalQueues.Values.Sum((q) => q.Count);
add tests

2023-01-02 20:05 UTC, noamyogev84 commented on ConcurrentPriorityQueue/Core/ConcurrentPriorityQueue.cs
> +                    .TapError(err => Result.Failure(err));
Can you please explain this change?

2023-01-03 04:57 UTC, zhuxb711 commented on ConcurrentPriorityQueue/ConcurrentPriorityQueue.csproj
>    </ItemGroup>
> warning : The .NET SDK has newer analyzers with version '7.0.0' than what version '5.0.3' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package reference

This is added by Visual Studio automatically. If you want, it's ok to remove it

2023-01-03 05:12 UTC, zhuxb711 commented on ConcurrentPriorityQueue/Core/ConcurrentPriorityQueue.cs
> +        public int Count => _internalQueues.Values.Sum((q) => q.Count);
We have 2 tests for Count already.
https://github.com/noamyogev84/ConcurrentPriorityQueue/blob/e512c33078d336904aee42e83b45630df3165081/ConcurrentPriorityQueueTests/PriorityQueueIEnumerabeUnitTests.cs#L56
https://github.com/noamyogev84/ConcurrentPriorityQueue/blob/e512c33078d336904aee42e83b45630df3165081/ConcurrentPriorityQueueTests/PriorityQueueIEnumerabeUnitTests.cs#L70

2023-01-03 05:20 UTC, zhuxb711 commented on ConcurrentPriorityQueue/Core/ConcurrentPriorityQueue.cs
> +                    .TapError(err => Result.Failure(err));
Ok, in the latest "CSharpFunctionalExtensions", ***OnSuccess()***, ***OnFailure()*** and ***Result.Fail()*** is already marked as ***"Obsolete"***. So I use ***Map()*** instead of ***OnSuccess()***, use ***TapError()*** instead of ***OnFailure()*** and use ***Result.Failure()*** instead of ***Result.Fail()***. 

**No behavior changes here.**

![image](https://user-images.githubusercontent.com/42038175/210303382-9f74af73-c7a8-4f5a-87cc-f5ac0c17875c.png)
![image](https://user-images.githubusercontent.com/42038175/210303491-6a4267b9-9975-4605-930d-0ab16bfea142.png)

2023-01-04 17:41 UTC, zhuxb711 commented
@noamyogev84 Hi I updated the code and replied your comments, please help review it again, thanks! 😃

2023-01-09 02:06 UTC, zhuxb711 commented
@noamyogev84 Hi! Could please take a look at the changes and maybe approve this PR? Thanks and very appreciate!

2023-01-09 09:18 UTC, noamyogev84 commented on ConcurrentPriorityQueue/Core/ConcurrentPriorityQueue.cs
> +                    .TapError(err => Result.Failure(err));
Fantastic! thx :clap:

2023-01-09 09:21 UTC, noamyogev84 commented
Thanks @zhuxb711 wonderful work 🎉

2023-01-09 16:15 UTC, zhuxb711 commented
Thanks for your approval, but there are some problems in the workflow file, I have updated them to make sure the repo could be built with the latest .Net 7.0, and make I request another approval to run the flow again? Thanks~~😁😎

2023-01-10 06:52 UTC, noamyogev84 approved these changes

2023-01-10 06:54 UTC, merged

2023-01-10 08:09 UTC, zhuxb711 commented
Thanks! @noamyogev84 Glad to hear that the PR was merged, thanks again and hopefully we could found the new version on nuget soon~ Your repo is the best ConcurrentPriorityQueue implementation I have ever seen. Looking forward to your new nuget package~

2023-01-10 13:08 UTC, noamyogev84 commented
Thanks @zhuxb711, I really enjoyed reviewing your code 🎉
Fron now on - **Our** repo.

Regarding Nuget: I will have to make some time for this in the coming weeks. 🙏
I encourage you to maybe think of a pipeline/action/automated release for Nuget releases and implement in here

2023-01-11 16:42 UTC, zhuxb711 commented
You could use this action for nuget release. Since it needs your nuget key and you should place it in your action secret. It would be better let you handle this action.

https://github.com/brandedoutcast/publish-nuget

2023-01-11 16:43 UTC, zhuxb711 commented
But maybe you could upload a new nuget package manually first so that we will not wait too long~~

2023-01-16 21:45 UTC, noamyogev84 commented
Yo,
Nuget 2.0.0 published. 🎉

On Wed, Jan 11, 2023 at 6:43 PM Ruofan ***@***.***> wrote:

> But maybe you could upload a new nuget package manually first so that we
> will not wait too long~~
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/noamyogev84/ConcurrentPriorityQueue/pull/19#issuecomment-1379130851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB26MJPIZJNWSGOAATJ7KS3WR3PMNANCNFSM6AAAAAATMYBF7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-17 08:18 UTC, zhuxb711 commented
![image](https://user-images.githubusercontent.com/42038175/212844824-9fcb0a93-2e97-4f55-a626-7bc118677d9a.png)

@noamyogev84 I got 1.0.0 from nuget still......Anything wrong?

2023-01-17 16:13 UTC, noamyogev84 commented
something went wrong
working on it

On Tue, Jan 17, 2023 at 10:18 AM Ruofan ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/42038175/212844824-9fcb0a93-2e97-4f55-a626-7bc118677d9a.png>
>
> @noamyogev84 <https://github.com/noamyogev84> I got 1.0.0 from nuget
> still......Anything wrong?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/noamyogev84/ConcurrentPriorityQueue/pull/19#issuecomment-1385004353>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB26MJMUQJPQ3MAA3PZ7CITWSZIWDANCNFSM6AAAAAATMYBF7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-17 19:21 UTC, noamyogev84 commented
Done

On Tue, Jan 17, 2023, 18:12 Noam Yogev ***@***.***> wrote:

> something went wrong
> working on it
>
> On Tue, Jan 17, 2023 at 10:18 AM Ruofan ***@***.***> wrote:
>
>> [image: image]
>> <https://user-images.githubusercontent.com/42038175/212844824-9fcb0a93-2e97-4f55-a626-7bc118677d9a.png>
>>
>> @noamyogev84 <https://github.com/noamyogev84> I got 1.0.0 from nuget
>> still......Anything wrong?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/noamyogev84/ConcurrentPriorityQueue/pull/19#issuecomment-1385004353>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AB26MJMUQJPQ3MAA3PZ7CITWSZIWDANCNFSM6AAAAAATMYBF7A>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>